return {
        cmd = { "tailwindcss-language-server", "--stdio" },
        filetypes = {
                "astro",
                "clojure",
                "htmldjango",
                "elixir",
                "eruby",
                "haml",
                "html",
                "htmlangular",
                "heex",
                "liquid",
                "markdown",
                "php",
                "css",
                "less",
                "sass",
                "scss",
                "stylus",
                "javascript",
                "javascriptreact",
                "rescript",
                "typescript",
                "typescriptreact",
                "vue",
                "svelte",
        },
        root_markers = {
                "tailwind.config.js",
                "tailwind.config.cjs",
                "tailwind.config.mjs",
                "tailwind.config.ts",
                "postcss.config.js",
                "postcss.config.cjs",
                "postcss.config.mjs",
                "postcss.config.ts",
                ".git",
        },
        settings = {
                tailwindCSS = {
                        classAttributes = { "class", "className", "class:list", "classList", "ngClass" },
                        includeLanguages = {
                                eruby = "erb",
                                htmlangular = "html",
                        },
                        lint = {
                                cssConflict = "warning",
                                invalidApply = "error",
                                invalidConfigPath = "error",
                                invalidScreen = "error",
                                invalidTailwindDirective = "error",
                                invalidVariant = "error",
                                recommendedVariantOrder = "warning",
                        },
                        validate = true,
                },
        },
}
