command_timeout = 1000

[battery]
disabled = true

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "yellow"
symbol = "🅰 "
[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "va"
eu-west-1 = "eu-w1"
eu-central-1 = "eu-c1"

[docker_context]
disabled = true
