matches:
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d-%m-%Y"

  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  - trigger: "api"
    replace: "API"

  - trigger: "python"
    replace: "Python"

  # Capitalize the first character of a sentence
  - regex: (?P<before>\w\[.?])\s(?P<firstchar>[a-z])(?P<therest>\w*\s)
    replace: "{{before}} {{capital}}{{therest}}"
    vars:
      - name: capital
        type: shell
        params:
          cmd: "echo \"${ESPANSO_FIRSTCHAR^}\""

  # Snippets
  - trigger: "rtrace"
    replace: "RUST_BACKTRACE=1 "

  - trigger: ":coauthor"
    replace: "Co-authored-by: name <@.COM>"
