matches:
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: ":dtime"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y %H:%M"
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"
  # Snippets
  - trigger: ":rtrace"
    replace: "RUST_BACKTRACE=1 "
  - trigger: ":coauthor"
    replace: "Co-authored-by: name <@.com>"
  - trigger: ":linkedin"
    replace: "https://www.linkedin.com/in/shayegan-hooshyari"
  - trigger: ":site"
    replace: "https://glyphack.com"
