matches:
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # Snippets
  - trigger: "rtrace"
    replace: "RUST_BACKTRACE=1 "

  - trigger: ":coauthor"
    replace: "Co-authored-by: name <@.COM>"
  - trigger: ":linkedin"
    replace: "https://www.linkedin.com/in/shayegan-hooshyari"

  - trigger: ":site"
    replace: "https://glyphack.com"
